config/routes.rb
Rails.application.routes.draw do
  root to: 'artists#index'

  resources :artists, only: :show do
    resources :albums, only: [:new, :create]
    resources :artist_tags, as: :tags, only: [:new, :create]
  end

  resources :albums, only: :destroy
end

app/models/album.rb
class Album < ApplicationRecord
  belongs_to :artist

  validates :title, :image_url, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :albums, dependent: :destroy
  has_many :artist_tags, dependent: :destroy
  has_many :tags, through: :artist_tags

  validates :name, presence: true, uniqueness: true
  validates :image_url, presence: true
end

app/models/artist_tag.rb
class ArtistTag < ApplicationRecord
  belongs_to :artist
  belongs_to :tag

  validates :tag, uniqueness: {
                                scope: :artist,
                                message: 'has already been added'
                              }
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :artist_tags, dependent: :destroy
  has_many :artists, through: :artist_tags

  validates :name, presence: true, uniqueness: { insensitive: true }

  def self.list_names
    pluck(:name).map(&:capitalize).sort
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_artist, except: :destroy

  def new
    @album = Album.new
  end

  def create
    @album = Album.new(album_params)
    @album.artist = @artist

    if @album.save
      redirect_to @artist
    else
      render :new
    end
  end

  def destroy
    @album = Album.find(params[:id])
    @album.destroy

    redirect_to @album.artist
  end

  private

  def set_artist
    @artist = Artist.find(params[:artist_id])
  end

  def album_params
    params.require(:album).permit(:title, :image_url)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/artist_tags_controller.rb
class ArtistTagsController < ApplicationController
  before_action :set_artist

  def new
    @artist_tag = ArtistTag.new
  end

  def create
    names = params[:artist_tag][:tag].reject(&:empty?).map(&:downcase)
    names.each do |name|
      tag = Tag.find_or_create_by(name: name)
      ArtistTag.create(artist: @artist, tag: tag)
    end

    redirect_to @artist
  end

  private

  def set_artist
    @artist = Artist.find(params[:artist_id])
  end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index
    @artists = Artist.all
  end

  def show
    @artist = Artist.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/albums/_album.html.erb
<div class="col-xs-12 col-sm-4">
  <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= album.image_url %>');">
    <div class="card-description">
      <h2><%= album.title %></h2>
    </div>
    <%= link_to "+", album_path(album), method: :delete, data: { confirm: "Are you sure?" }, class: "card-remove-link" %>
  </div>
</div>

app/views/albums/new.html.erb
<h1>Add Album</h1>

<%= simple_form_for [@artist, @album] do |f| %>
  <%= f.input :title %>
  <%= f.input :image_url %>

  <%= f.submit class: 'btn btn-primary' %>
<% end  %>

app/views/artist_tags/new.html.erb
<h1>Add tags to <%= @artist.name %></h1>
<div class="row">
  <div class="col-sm-6">
    <%= simple_form_for @artist_tag do |f| %>
      <%= f.input :tag, collection: Tag.list_names,
                  include_blank: false,
                  include_hidden: false,
                  input_html: { multiple: true }
      %>

      <%= f.button :submit, 'Save', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/artists/index.html.erb
<h1>Artists</h1>

<div id="artists">
  <% @artists.each do |artist| %>
    <div class="artist">
      <%= link_to artist_path(artist) do %>
        <%= image_tag artist.image_url, class: "avatar-xxl" %>
        <h5 class="text-center"><%= artist.name %></h5>
      <% end %>
    </div>
  <% end %>
</div>

app/views/artists/show.html.erb
<div class="artist-header">
  <div class="avatar-xxl">
    <%= image_tag @artist.image_url, class: "avatar-xxl" %>
  </div>
  <div class="artist-menu">
    <h1><%= @artist.name %></h1>
    <div class="artist-tags">
      <% @artist.tags.each do |tag| %>
        <span class="tag"><%= tag.name %></span>
      <% end %>
    </div>
    <%= link_to "Artists", root_path  %> |
    <%= link_to "Add Album", new_artist_album_path(@artist) %> |
    <%= link_to "Add Tags", new_artist_tag_path(@artist) %>
  </div>
</div>

<div id="albums">
  <h2>Releases</h2>
  <% if @artist.albums.any? %>
    <div class="container-fluid">
      <div class="row">
        <% @artist.albums.each do |album| %>
          <div class="col-xs-12 col-sm-4">
            <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= album.image_url %>');">
              <div class="card-description">
                <h2><%= album.title %></h2>
              </div>
              <%= link_to "+", album_path(album), method: :delete, data: { confirm: "Are you sure?" }, class: "card-remove-link" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  <% else %>
    <p>This artist has no releases yet!</p>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Airtunes258</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="page-wrapper">
      <%= yield %>
    </div>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>